remedies = {
    "corn_cercospora_leaf_spot": "Use fungicides like azoxystrobin. Practice crop rotation and remove infected debris.",
    "corn_common_rust": "Apply fungicides such as tebuconazole. Plant resistant hybrids.",
    "corn_gray_leaf_spot": "Use resistant varieties and practice crop rotation.",
    "corn_northern_leaf_blight": "Apply fungicides and use resistant hybrids.",
    "cotton_aphids": "Use insecticides like imidacloprid. Promote natural predators like ladybugs.",
    "cotton_army_worm": "Apply Bacillus thuringiensis (Bt) or neem-based insecticides.",
    "cotton_bacterial_blight": "Use resistant varieties and certified disease-free seeds.",
    "cotton_powdery_mildew": "Apply sulfur-based or systemic fungicides like triadimefon.",
    "cotton_target_spot": "Use strobilurin fungicides and maintain field hygiene.",
    "grape_black_rot": "Apply fungicides like mancozeb or myclobutanil. Remove mummified fruits.",
    "grape_esca_black_measles": "Prune infected vines. Use protective fungicides early in the season.",
    "grape_leaf_blight": "Use copper-based fungicides and improve air circulation.",
    "groundnut_early_leaf_spot": "Apply chlorothalonil or tebuconazole. Rotate with non-legumes.",
    "groundnut_late_leaf_spot": "Use fungicides like hexaconazole. Destroy plant residues.",
    "groundnut_nutrition_deficiency": "Apply gypsum or lime, and ensure adequate calcium and boron.",
    "groundnut_rust": "Spray with systemic fungicides like tebuconazole.",
    "healthy_corn": "No remedy needed. Crop appears healthy.",
    "healthy_cotton": "No remedy needed. Crop appears healthy.",
    "healthy_grape": "No remedy needed. Crop appears healthy.",
    "healthy_groundnut": "No remedy needed. Crop appears healthy.",
    "healthy_lemon": "No remedy needed. Crop appears healthy.",
    "healthy_potato": "No remedy needed. Crop appears healthy.",
    "healthy_sugarcane": "No remedy needed. Crop appears healthy.",
    "healthy_tomato": "No remedy needed. Crop appears healthy.",
    "healthy_wheat": "No remedy needed. Crop appears healthy.",
    "lemon_anthracnose": "Use copper-based fungicides and prune infected parts.",
    "lemon_bacterial_blight": "Apply copper oxychloride and avoid overhead watering.",
    "lemon_citrus_canker": "Use streptomycin sprays and remove infected plant material.",
    "lemon_curl_virus": "Control aphids and whiteflies. Remove infected plants.",
    "lemon_deficiency": "Use balanced fertilizers, especially micronutrients like zinc and magnesium.",
    "lemon_dry_leaf": "Improve irrigation and apply potassium-rich fertilizers.",
    "lemon_sooty_mould": "Control sap-sucking insects and wash leaves with water.",
    "lemon_spider_mites": "Use miticides or neem oil. Keep humidity levels up.",
    "potato_early_blight": "Apply fungicides like chlorothalonil or mancozeb.",
    "potato_late_blight": "Use systemic fungicides like metalaxyl. Avoid overhead irrigation.",
    "soyabean_sudden_death_syndrome": "Plant resistant varieties and improve drainage.",
    "soyabean_bacterial_blight": "Use disease-free seeds and rotate with non-host crops.",
    "soyabean_healthy": "No remedy needed. Crop appears healthy.",
    "sugarcane_bacterial_blight": "Use resistant varieties and disinfect tools.",
    "sugarcane_mosaic": "Control aphid vectors. Use virus-free planting material.",
    "sugarcane_red_rot": "Use resistant varieties and remove infected clumps.",
    "sugarcane_rust": "Spray with fungicides like triadimefon. Remove infected leaves.",
    "sugarcane_yellow_leaf": "Plant virus-free seed cane. Control aphids.",
    "tomato_bacterial_spot": "Use copper sprays and resistant varieties.",
    "tomato_early_blight": "Apply mancozeb or chlorothalonil. Remove infected debris.",
    "tomato_late_blight": "Use fungicides like metalaxyl and avoid water splash.",
    "tomato_septoria_leaf_spot": "Use fungicides like chlorothalonil and remove lower leaves.",
    "tomato_yellow_leaf_curl_virus": "Control whiteflies. Remove infected plants promptly.",
    "wheat_aphid": "Use insecticides like acetamiprid. Encourage natural predators.",
    "wheat_black_rust": "Spray fungicides such as propiconazole early.",
    "wheat_blast": "Apply triazole fungicides and use clean seed.",
    "wheat_brown_rust": "Spray fungicides and plant resistant varieties.",
    "wheat_common_root_rot": "Rotate with non-host crops and treat seeds with fungicide.",
    "wheat_fusarium_head_blight": "Use resistant varieties. Avoid dense planting.",
    "wheat_leaf_blight": "Apply protective fungicides and improve drainage.",
    "wheat_mildew": "Use sulfur dust or fungicides. Ensure adequate airflow.",
    "wheat_mite": "Spray with acaricides and maintain field hygiene.",
    "wheat_septoria": "Use strobilurin or azole fungicides.",
    "wheat_smut": "Treat seeds with fungicides like carboxin.",
    "wheat_stem_fly": "Apply systemic insecticides at sowing.",
    "wheat_tan_spot": "Use fungicides like propiconazole and practice rotation.",
    "wheat_yellow_rust": "Spray with fungicides such as tebucanozole or triazoles."
}
