from typing import Any, Dict, List

# Comprehensive Maize Lifecycle spanning 19 stages from Sowing to Physiological Maturity
MAIZE_LIFECYCLE_STAGES: List[Dict[str, Any]] = [
    {
        "stage_id": "sowing",
        "order": 1,
        "name_en": "Sowing (Day 0-3)",
        "name_mr": "पेरणी (०-३ दिवस)",
        "day_range_min": 0,
        "day_range_max": 3,
        "description_en": "Seed placed in soil. Seed absorbs moisture to begin germination.",
        "description_mr": "बियाणे जमिनीत पेरले जाते आणि ओलावा शोषून घेण्यास सुरुवात करते.",
        "npk_recommendation": {
            "title_en": "Basal Fertilizer Dose (At Sowing)",
            "title_mr": "पायाभूत खत मात्रा (पेरणीवेळी)",
            "per_acre_kg": {"DAP_18_46_0": 50, "MOP_0_0_60": 30, "Zinc_Sulphate": 10},
            "instruction_en": "Apply basal fertilizers 5 cm away and below seed level.",
            "instruction_mr": "पेरणीच्या वेळी रासायनिक खते बियाण्याखाली ५ सेमी खोल द्या.",
        },
        "irrigation_advice_en": "Apply light first irrigation immediately after sowing.",
        "irrigation_advice_mr": "पेरणीनंतर लगेच हलके पाणी (ओलवणी) द्या.",
        "water_sensitivity": "Moderate",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "germination",
        "order": 2,
        "name_en": "Germination (Day 4-6)",
        "name_mr": "उगवण (४-६ दिवस)",
        "day_range_min": 4,
        "day_range_max": 6,
        "description_en": "Radicle (primary root) and coleoptile emerge from the seed.",
        "description_mr": "बियाण्यामधून प्राथमिक मूळ आणि मोड बाहेर येतात.",
        "irrigation_advice_en": "Second light irrigation if topsoil is crusty.",
        "irrigation_advice_mr": "जमीन टणक झाल्यास दुसरे हलके पाणी द्या.",
        "water_sensitivity": "Low",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "ve_emergence",
        "order": 3,
        "name_en": "VE - Emergence (Day 7-9)",
        "name_mr": "व्हीई - रोपे बाहेर येणे (७-९ दिवस)",
        "day_range_min": 7,
        "day_range_max": 9,
        "description_en": "Coleoptile breaks soil surface. Plant relies on seed reserves.",
        "description_mr": "रोपे जमिनीच्या वर येतात. रोप बियाण्यातील अन्नावर अवलंबून असते.",
        "water_sensitivity": "Low",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "v1_first_leaf",
        "order": 4,
        "name_en": "V1 - First Leaf (Day 10-12)",
        "name_mr": "व्ही१ - पहिले पान (१०-१२ दिवस)",
        "day_range_min": 10,
        "day_range_max": 12,
        "description_en": "First leaf with rounded tip fully emerges with a visible collar.",
        "description_mr": "गोल टोक असलेले पहिले पान पूर्णपणे बाहेर येते.",
        "water_sensitivity": "Low",
        "pest_disease_watch": [
            {
                "threat_en": "Fall Armyworm (FAW) Egg masses",
                "threat_mr": "लष्करी अळीचे अंडीपुंज",
                "action_en": "Scout underside of leaves. Install 5 pheromone traps per acre.",
                "action_mr": "पानांच्या खालच्या बाजूस अंड्यांचे निरीक्षण करा. एकरी ५ फेरोमोन ट्रॅप लावा.",
            },
        ],
        "default_tasks": [
            {
                "title_en": "Install Pheromone Traps for FAW Monitoring",
                "title_mr": "लष्करी अळी नियंत्रणासाठी एकरी ५ कामगंध सापळे लावणे",
                "task_type": "cultural",
                "due_days": 10,
            },
        ],
    },
    {
        "stage_id": "v2_second_leaf",
        "order": 5,
        "name_en": "V2 - Second Leaf (Day 13-16)",
        "name_mr": "व्ही२ - दुसरे पान (१३-१६ दिवस)",
        "day_range_min": 13,
        "day_range_max": 16,
        "description_en": "Second leaf fully unrolled. Seminal roots provide nutrients.",
        "description_mr": "दुसरे पान पूर्णपणे उघडते. मुळांद्वारे अन्नद्रव्ये शोषण्यास सुरुवात.",
        "water_sensitivity": "Low",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "v3_third_leaf",
        "order": 6,
        "name_en": "V3 - Third Leaf (Day 17-20)",
        "name_mr": "व्ही३ - तिसरे पान (१७-२० दिवस)",
        "day_range_min": 17,
        "day_range_max": 20,
        "description_en": "Nodal root system begins developing. Plant transition from seed reserves to soil nutrients.",
        "description_mr": "मुख्य मुळांची वाढ सुरू होते. रोपे आता जमिनीतील अन्नद्रव्यांवर अवलंबून असतात.",
        "water_sensitivity": "Moderate",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "v4_fourth_leaf",
        "order": 7,
        "name_en": "V4 - Fourth Leaf (Day 21-24)",
        "name_mr": "व्ही४ - चौथे पान (२१-२४ दिवस)",
        "day_range_min": 21,
        "day_range_max": 24,
        "description_en": "Rapid leaf and root growth. First top-dressing preparation.",
        "description_mr": "पानांची आणि मुळांची वेगवान वाढ. खतांच्या पहिल्या मात्रेची तयारी.",
        "water_sensitivity": "Moderate",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "v5_fifth_leaf",
        "order": 8,
        "name_en": "V5 - Fifth Leaf (Day 25-28)",
        "name_mr": "व्ही५ - पाचवे पान (२५-२८ दिवस)",
        "day_range_min": 25,
        "day_range_max": 28,
        "description_en": "Microscopic tassel initiates inside the stem.",
        "description_mr": "खोडामध्ये सूक्ष्म तुरा (नर फुल) तयार व्हायला सुरुवात होते.",
        "npk_recommendation": {
            "title_en": "First Top-Dressing (Urea)",
            "title_mr": "पहिली खताची मात्रा (युरिया)",
            "per_acre_kg": {"Urea": 45, "Magnesium_Sulphate": 10},
            "instruction_en": "Top-dress Urea followed by earthing up and immediate irrigation.",
            "instruction_mr": "युरिया खत देऊन मातीची भर लावा व पाणी द्या.",
        },
        "water_sensitivity": "High",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "v6_sixth_leaf",
        "order": 9,
        "name_en": "V6 - Sixth Leaf (Day 29-33)",
        "name_mr": "व्ही६ - सहावे पान (२९-३३ दिवस)",
        "day_range_min": 29,
        "day_range_max": 33,
        "description_en": "Growing point emerges above the soil surface. Stem rapid elongation.",
        "description_mr": "वाढीचा बिंदू जमिनीच्या वर येतो. खोडाची वेगाने वाढ होते.",
        "irrigation_advice_en": "Irrigate every 8-10 days depending on soil moisture.",
        "irrigation_advice_mr": "जमिनीतील ओलावा पाहून ८ ते १० दिवसांनी पाणी द्या.",
        "water_sensitivity": "High",
        "pest_disease_watch": [
            {
                "threat_en": "Fall Armyworm Whorl Feeding",
                "threat_mr": "मक्याच्या पोंग्यातील लष्करी अळी",
                "action_en": "Spray Chlorantraniliprole 18.5% SC @ 0.4 ml/L directly into whorl.",
                "action_mr": "कोराजन ६ मिली प्रति १५ लिटर पंप थेट पोंग्यात फवारा.",
            }
        ],
        "default_tasks": [],
    },
    {
        "stage_id": "v7_v9_rapid_growth",
        "order": 10,
        "name_en": "V7-V9 Rapid Elongation (Day 34-42)",
        "name_mr": "व्ही७-व्ही९ - वेगवान वाढ (३४-४२ दिवस)",
        "day_range_min": 34,
        "day_range_max": 42,
        "description_en": "Potential rows per ear (cob) are determined. Leaves emerge quickly.",
        "description_mr": "कणसातील दाण्यांच्या रांगांची संख्या निश्चित होते. पाने वेगाने वाढतात.",
        "water_sensitivity": "High",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "v10_v12_nutrient_peak",
        "order": 11,
        "name_en": "V10-V12 Nutrient Peak Demand (Day 43-52)",
        "name_mr": "व्ही१०-व्ही१२ - अन्नद्रव्यांची सर्वाधिक गरज (४३-५२ दिवस)",
        "day_range_min": 43,
        "day_range_max": 52,
        "description_en": "Rapid accumulation of dry matter and nutrients.",
        "description_mr": "झाडाचे वजन आणि अन्नद्रव्यांचे शोषण वेगाने वाढते.",
        "npk_recommendation": {
            "title_en": "Second Top-Dressing",
            "title_mr": "दुसरी खताची मात्रा",
            "per_acre_kg": {"Urea": 35, "MOP_0_0_60": 20},
            "instruction_en": "Apply Potash alongside Urea to strengthen stalk against lodging.",
            "instruction_mr": "खोड मजबूत होण्यासाठी युरियासोबत पोटॅश खत द्या.",
        },
        "water_sensitivity": "High",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "v13_v15_late_veg",
        "order": 12,
        "name_en": "V13-V15 Late Vegetative (Day 53-60)",
        "name_mr": "व्ही१३-व्ही१५ - उशिरा शाकीय वाढ (५३-६० दिवस)",
        "day_range_min": 53,
        "day_range_max": 60,
        "description_en": "Brace roots fully formed. Tassel is nearing emergence.",
        "description_mr": "आधार मुळे पूर्णपणे विकसित. तुरा बाहेर येण्याची वेळ जवळ.",
        "water_sensitivity": "High",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "vt_tasseling",
        "order": 13,
        "name_en": "VT - Tasseling (Day 61-68)",
        "name_mr": "व्हीटी - तुरा येणे (६१-६८ दिवस)",
        "day_range_min": 61,
        "day_range_max": 68,
        "description_en": "Tassel fully emerged and sheds pollen.",
        "description_mr": "तुरा (नर फूल) पूर्णपणे बाहेर येतो आणि परागकण सोडतो.",
        "irrigation_advice_en": "CRITICAL MOISTURE PERIOD: Water stress can reduce yield by up to 40%.",
        "irrigation_advice_mr": "अतिसंवेदनशील टप्पा: पाण्याचा ताण पडल्यास उत्पन्नात मोठी घट होऊ शकते.",
        "water_sensitivity": "Critical",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "r1_silking",
        "order": 14,
        "name_en": "R1 - Silking (Day 69-75)",
        "name_mr": "आर१ - रेशीम अवस्था (६९-७५ दिवस)",
        "day_range_min": 69,
        "day_range_max": 75,
        "description_en": "Silks emerge from cob. Pollination occurs.",
        "description_mr": "कणसातून रेशीम (केस) बाहेर पडते. परागीभवन होते.",
        "npk_recommendation": {
            "title_en": "Foliar Spray",
            "title_mr": "विद्राव्य खताची फवारणी",
            "per_acre_kg": {"NPK_0_0_50": 2, "Boron_20_percent": 0.25},
            "instruction_en": "Foliar spray of 0:0:50 + Boron enhances grain size.",
            "instruction_mr": "००:००:५० + बोरॉन फवारणी केल्याने दाणे टपोरे भरतात.",
        },
        "water_sensitivity": "Critical",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "r2_blister",
        "order": 15,
        "name_en": "R2 - Blister (Day 76-85)",
        "name_mr": "आर२ - फोड अवस्था (७६-८५ दिवस)",
        "day_range_min": 76,
        "day_range_max": 85,
        "description_en": "Kernels resemble white blisters filled with clear fluid.",
        "description_mr": "दाणे पांढऱ्या फोडासारखे दिसतात आणि त्यात पारदर्शक द्रव असतो.",
        "water_sensitivity": "High",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "r3_milk",
        "order": 16,
        "name_en": "R3 - Milk (Day 86-95)",
        "name_mr": "आर३ - दुधाळ अवस्था (८६-९५ दिवस)",
        "day_range_min": 86,
        "day_range_max": 95,
        "description_en": "Kernel fluid turns milky white. Dry matter accumulates rapidly.",
        "description_mr": "दाण्यातील द्रव दुधाळ पांढरा होतो. दाण्यांचे वजन वेगाने वाढते.",
        "water_sensitivity": "High",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "r4_dough",
        "order": 17,
        "name_en": "R4 - Dough (Day 96-105)",
        "name_mr": "आर४ - पीठ अवस्था (९६-१०५ दिवस)",
        "day_range_min": 96,
        "day_range_max": 105,
        "description_en": "Milky fluid thickens to a dough-like consistency.",
        "description_mr": "दुधाळ द्रव घट्ट होऊन पिठासारखा होतो.",
        "water_sensitivity": "Moderate",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "r5_dent",
        "order": 18,
        "name_en": "R5 - Dent (Day 106-115)",
        "name_mr": "आर५ - डेंट (खड्डा) अवस्था (१०६-११५ दिवस)",
        "day_range_min": 106,
        "day_range_max": 115,
        "description_en": "Starch hardens at the kernel crown causing a dent.",
        "description_mr": "दाण्याच्या वरच्या बाजूला स्टार्च कडक होऊन खड्डा पडतो.",
        "water_sensitivity": "Low",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
    {
        "stage_id": "r6_maturity",
        "order": 19,
        "name_en": "R6 - Physiological Maturity (Day 116+)",
        "name_mr": "आर६ - पक्वता (११६+ दिवस)",
        "day_range_min": 116,
        "day_range_max": 130,
        "description_en": "Black layer forms. Maximum dry weight achieved. Ready for harvest when dry.",
        "description_mr": "दाण्याच्या तळाशी काळा ठिपका तयार होतो. पीक काढणीस तयार.",
        "water_sensitivity": "None",
        "pest_disease_watch": [],
        "default_tasks": [],
    },
]

def get_current_stage(days_since_sowing: int) -> Dict[str, Any]:
    for stage in MAIZE_LIFECYCLE_STAGES:
        if stage["day_range_min"] <= days_since_sowing <= stage["day_range_max"]:
            return stage
    return MAIZE_LIFECYCLE_STAGES[-1]

def calculate_fertilizer_dosage_for_acres(acreage: float, stage_id: str) -> Dict[str, Any]:
    stage = next((s for s in MAIZE_LIFECYCLE_STAGES if s["stage_id"] == stage_id), None)
    if not stage or "npk_recommendation" not in stage:
        return {}

    npk = stage["npk_recommendation"]
    per_acre = npk.get("per_acre_kg", {})
    calculated = {}
    for fert_name, kg_per_acre in per_acre.items():
        calculated[fert_name] = round(kg_per_acre * acreage, 1)

    return {
        "title_en": npk.get("title_en"),
        "title_mr": npk.get("title_mr"),
        "acreage": acreage,
        "fertilizers_kg": calculated,
        "instruction_en": npk.get("instruction_en"),
        "instruction_mr": npk.get("instruction_mr"),
    }

def get_all_stages() -> List[Dict[str, Any]]:
    return MAIZE_LIFECYCLE_STAGES
